/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 08:32:22 GMT 2020
 */

package me.ilcb.adapter.clazz;

import org.junit.Test;
import static org.junit.Assert.*;
import me.ilcb.adapter.clazz.Client;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Client_ESTest extends Client_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Client client0 = new Client();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[2];
      Client.main(stringArray0);
      assertEquals(2, stringArray0.length);
  }
}
