/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 08:32:54 GMT 2020
 */

package me.ilcb.adapter.object;

import org.junit.Test;
import static org.junit.Assert.*;
import me.ilcb.adapter.object.Target;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      target0.request();
  }
}
